version: '3.3'
services:
  tezos-node:
    build: .
    network_mode: host
    command: bash -c "node index.js start tezos-node; node index.js start tezos-node && while true; do sleep 30; done;"
  ganache:
    build: .
    network_mode: host
    command: >
      bash -c "
        while ! nc -z localhost 3030; do
          sleep 1
        done
        ganache-cli --port 9545 --blockTime 12 --gasLimit 10000000 --account='0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501200,10000000000000000000000000000'
      "
  eth2tezos-relay:
    build: .
    network_mode: host
    depends_on:
      - ganache
    command: >
      bash -c "
        while ! nc -z localhost 9545; do
          sleep 1
        done
        node index.js init-tezos-contracts &&
        node index.js start eth2tezos-relay --daemon false
      "
